{{- if .Values.prometheusVolume.enabled }}
{{- $name := .Values.prometheusVolume.name -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.prometheusVolume.volumeHandle }}
{{- end }}
