{{- if .Values.dockerHub.enabled }}
{{- $name := .Values.dockerHub.secret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.dockerHub.secret.dockercfg | squote }}
{{- end }}
