{{- if .Values.ingress.internal.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "example-apps-stack.fullname" . }}-internal
  labels:
    {{- include "example-apps-stack.labels" . | nindent 4 }}
  {{- with .Values.ingress.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.internal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .backend.serviceName }}
              servicePort: {{ .backend.servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
